course: "CS56"
qtr: "M18"
quarter: "Summer 2018"
piazza_url: https://piazza.com/class/tbd
gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=tbd
github_org_name: ucsb-cs56-m18
github_org_url: https://github.com/ucsb-cs56-m18

ta_list: "Mahnaz and Santha"
ta_list_full: "Mahnaz Koupaee and Santha Ramamoorthy"
mentors_list: "Chandler, Charlie (Fuheng) Derek (Guancheng), Nuan, Omer, Wilson, Yunkai, Zihao"
discussion_section_times: "9:30am, 11am"

github_url: https://github.com/ucsb-cs56-m18/ucsb-cs56-m18.github.io
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"

submit_cs_course: CS56_m18

start_week: 1
start_date: 2018-08-05 00:00:00.00-8:00
num_weeks: 6
extra_exam_week: false
sections: "9:30am&nbsp;or&nbsp;11am"

cal_dates: >
  [
  {"label":"Session B classes begin", "date":"2018-08-06" },
    {"label":"YES WE DEFINITELY DO HAVE LAB THIS DAY", "date":"2018-09-14" },	

  {"label":"Session B classes end", "date":"2018-09-15" },	
  {"label":"Univ Holiday", "date":"2018-09-03" },
  ]

hwk_drop_lowest: three

legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"

kramdown:
   parse_block_html: true


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  bios:
    output: true
    permalink: /bios/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: bios
    values:
     layout: bio
